version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    expose:
      - "5000"
    networks:
      - internal_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
